/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ar.mycompany.conversor_divisa.Iug;

import ar.mycompany.conversor_divisa.Logica.Api;
import java.awt.Color;

/**
 *
 * @author Juan Bravo
 */
public class Pantalla_Moneda extends javax.swing.JFrame {
    int ejeX;
    int ejeY;

    /**
     * Creates new form Pantalla_Moneda
     */
    public Pantalla_Moneda() {
        initComponents();
        txtTotalMoneda.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtMoneda = new javax.swing.JTextField();
        cmbMoneda2 = new javax.swing.JComboBox<>();
        txtTotalMoneda = new javax.swing.JTextField();
        cmbMoneda1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        panelCierre = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        btnAtras = new javax.swing.JPanel();
        txtAtras = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JPanel();
        textConvertir = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 360));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(86, 105, 129));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 360));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DIVISA");

        TxtMoneda.setBackground(new java.awt.Color(86, 105, 129));
        TxtMoneda.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TxtMoneda.setForeground(new java.awt.Color(255, 255, 255));
        TxtMoneda.setText("Ingrese el Monto");
        TxtMoneda.setBorder(null);
        TxtMoneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtMonedaMousePressed(evt);
            }
        });
        TxtMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMonedaActionPerformed(evt);
            }
        });
        TxtMoneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMonedaKeyTyped(evt);
            }
        });

        cmbMoneda2.setBackground(new java.awt.Color(86, 105, 129));
        cmbMoneda2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        cmbMoneda2.setForeground(new java.awt.Color(0, 0, 0));
        cmbMoneda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "JPY", "KRW", "ARS" }));
        cmbMoneda2.setBorder(null);
        cmbMoneda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMoneda2ActionPerformed(evt);
            }
        });

        txtTotalMoneda.setBackground(new java.awt.Color(86, 105, 129));
        txtTotalMoneda.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtTotalMoneda.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalMoneda.setBorder(null);
        txtTotalMoneda.setPreferredSize(new java.awt.Dimension(105, 22));
        txtTotalMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMonedaActionPerformed(evt);
            }
        });

        cmbMoneda1.setBackground(new java.awt.Color(86, 105, 129));
        cmbMoneda1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        cmbMoneda1.setForeground(new java.awt.Color(0, 0, 0));
        cmbMoneda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "JPY", "KRW", "ARS" }));
        cmbMoneda1.setBorder(null);

        panelCierre.setBackground(new java.awt.Color(86, 105, 129));
        panelCierre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelCierreMouseDragged(evt);
            }
        });
        panelCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCierreMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(86, 105, 129));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        txtExit.setBackground(new java.awt.Color(137, 167, 177));
        txtExit.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtExit.setForeground(new java.awt.Color(204, 204, 204));
        txtExit.setText("     X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnAtras.setBackground(new java.awt.Color(86, 105, 129));
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtAtras.setFont(new java.awt.Font("Cascadia Mono PL SemiBold", 0, 24)); // NOI18N
        txtAtras.setForeground(new java.awt.Color(204, 204, 204));
        txtAtras.setText(" ←");
        txtAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelCierreLayout = new javax.swing.GroupLayout(panelCierre);
        panelCierre.setLayout(panelCierreLayout);
        panelCierreLayout.setHorizontalGroup(
            panelCierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCierreLayout.createSequentialGroup()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(460, 460, 460)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCierreLayout.setVerticalGroup(
            panelCierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnConvertir.setBackground(new java.awt.Color(137, 167, 177));
        btnConvertir.setForeground(new java.awt.Color(86, 105, 129));
        btnConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textConvertir.setBackground(new java.awt.Color(137, 167, 177));
        textConvertir.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        textConvertir.setForeground(new java.awt.Color(0, 0, 0));
        textConvertir.setText("           CONVERTIR");
        textConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textConvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textConvertirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textConvertirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textConvertirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConvertirLayout = new javax.swing.GroupLayout(btnConvertir);
        btnConvertir.setLayout(btnConvertirLayout);
        btnConvertirLayout.setHorizontalGroup(
            btnConvertirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnConvertirLayout.setVerticalGroup(
            btnConvertirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConvertirLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(TxtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(cmbMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(txtTotalMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(cmbMoneda2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMoneda2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMonedaActionPerformed
        

    }//GEN-LAST:event_txtTotalMonedaActionPerformed

    private void TxtMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMonedaActionPerformed

    private void TxtMonedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMonedaKeyTyped
        int key = evt.getKeyChar();
        
        boolean numeros = key >=48 && key<=57;
        
        if(!numeros){
            evt.consume();
         }
        
    }//GEN-LAST:event_TxtMonedaKeyTyped

    private void cmbMoneda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMoneda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMoneda2ActionPerformed

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(new Color(203,218,213));
        txtExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(new Color(86,105,129));
        txtExit.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_txtExitMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered

    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited

    }//GEN-LAST:event_btnExitMouseExited

    private void txtAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseClicked
        Pantalla_Inicio pantallaInicio = new Pantalla_Inicio();
        pantallaInicio.setVisible(true);
        pantallaInicio.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_txtAtrasMouseClicked

    private void txtAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseEntered
        btnAtras.setBackground(new Color(203,218,213));
        txtAtras.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtAtrasMouseEntered

    private void txtAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseExited
        btnAtras.setBackground(new Color(86,105,129));
        txtAtras.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_txtAtrasMouseExited

    private void panelCierreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCierreMouseDragged
        int xScreen = evt.getXOnScreen();
        int yScreen = evt.getYOnScreen();
        this.setLocation(xScreen - ejeX, yScreen - ejeY);
    }//GEN-LAST:event_panelCierreMouseDragged

    private void panelCierreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCierreMousePressed
        ejeX = evt.getX();
        ejeY = evt.getY();
    }//GEN-LAST:event_panelCierreMousePressed

    private void textConvertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textConvertirMouseClicked
        double monto =Double.valueOf(TxtMoneda.getText()) ;
        String monedaPrincipal = (String) cmbMoneda1.getSelectedItem();
        String monedaConversion = (String) cmbMoneda2.getSelectedItem();
        
         Api getApi = new Api();
         getApi.getApi(monedaPrincipal,monedaConversion,monto);
         double result = getApi.getResult();
         String resultString = String.valueOf(result);
         txtTotalMoneda.setText(resultString);
    }//GEN-LAST:event_textConvertirMouseClicked

    private void textConvertirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textConvertirMouseEntered
        btnConvertir.setBackground(new Color(203,218,213));
    }//GEN-LAST:event_textConvertirMouseEntered

    private void textConvertirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textConvertirMouseExited
        btnConvertir.setBackground(new Color(137,167,177));
    }//GEN-LAST:event_textConvertirMouseExited

    private void TxtMonedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtMonedaMousePressed
        TxtMoneda.setText("");
    }//GEN-LAST:event_TxtMonedaMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtMoneda;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnConvertir;
    private javax.swing.JPanel btnExit;
    private javax.swing.JComboBox<String> cmbMoneda1;
    private javax.swing.JComboBox<String> cmbMoneda2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel panelCierre;
    private javax.swing.JLabel textConvertir;
    private javax.swing.JLabel txtAtras;
    private javax.swing.JLabel txtExit;
    private javax.swing.JTextField txtTotalMoneda;
    // End of variables declaration//GEN-END:variables
}
